name: CI

# Cancel in-progress jobs if a new job is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        architecture: [x64, arm64]
        exclude:
          - os: macos-15
            architecture: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C compiler
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install build-essential
            sudo apt-get install clang
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install gcc
            # clang is already installed by default
          fi
      - name: Compile main.c with gcc
        run: |
          gcc -Werror -Wall -o checker-gcc src/main.c

      - name: Compile main.c with gcc + DEBUG
        run: |
          gcc -Werror -Wall -o checker-gcc-debug src/main.c -DDEBUG

      - name: Compile main.c with clang
        run: |
          clang -Werror -Wall -o checker-clang src/main.c

      - name: Compile main.c with clang + DEBUG
        run: |
          clang -Werror -Wall -o checker-clang-debug src/main.c -DDEBUG

      - name: Run the checker
        run: |
          ./checker-gcc -h
          ./checker-gcc-debug -h
          ./checker-clang -h
          ./checker-clang-debug -h
