name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C compiler
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install build-essential
            sudo apt-get install clang
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install gcc
            # clang is already installed by default
          fi
      - name: Compile checker.c with gcc and check output
        run: |
          gcc -Werror -Wall -o checker-gcc src/checker.c

      - name: Compile checker.c with clang
        run: |
          clang -Werror -Wall -o checker-clang src/checker.c

      - name: Run the checker
        run: |
          ./checker-gcc -h
          ./checker-clang -h
